courierApp: DistributedTravelingSalesman.Domain.Entities.GraphGenerator Class Reference
DistributedTravelingSalesman.Domain.Entities.GraphGenerator Class Reference
Public Member Functions
GraphGenerator ()
Graph GenerateGraph (int nodesCount)
IList< Node > GenerateRandomGraph (int nodesCount)
double[][] ConvertToMatrix (IList< Node > graph)
T[][] GetTwoDimensionalArray< T > (int size)
Private Attributes
readonly Random _random
Static Private Attributes
const int MinX = 0
const int MaxX = 1000
const int MinY = 0
const int MaxY = 1000
Detailed Description
Definition at line 7 of file GraphGenerator.cs.
Constructor & Destructor Documentation
GraphGenerator()
DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GraphGenerator () inline
Definition at line 15 of file GraphGenerator.cs.
        {
            _random = new Random();
        }
References DistributedTravelingSalesman.Domain.Entities.GraphGenerator._random.
Member Function Documentation
ConvertToMatrix()
double[][] DistributedTravelingSalesman.Domain.Entities.GraphGenerator.ConvertToMatrix (IList< Node > graph) inline
Definition at line 49 of file GraphGenerator.cs.
        {
            var graphMatrix = GetTwoDimensionalArray<double>(graph.Count);
            foreach (var node in graph)
            foreach (var edge in node.Edges)
            {
                var secondIndex = edge.FirstNode == node ? edge.SecondNode.Index : edge.FirstNode.Index;
                graphMatrix[node.Index][secondIndex] = edge.Weight;
            }
            return graphMatrix;
        }
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateGraph().
GenerateGraph()
Graph DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateGraph (int nodesCount) inline
Definition at line 20 of file GraphGenerator.cs.
        {
            var consistentGraph = GenerateRandomGraph(nodesCount);
            var graphDto = new Graph
            {
                AdjMatrix = ConvertToMatrix(consistentGraph)
            };
            return graphDto;
        }
References DistributedTravelingSalesman.Domain.Entities.GraphGenerator.ConvertToMatrix(), and DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph().
GenerateRandomGraph()
IList< Node > DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph (int nodesCount) inline
Definition at line 30 of file GraphGenerator.cs.
        {
            var graph = new List<Node>();
            for (var i = 0; i < nodesCount; i++)
            {
                var x = _random.Next(MinX, MaxX);
                var y = _random.Next(MinY, MaxY);
                graph.Add(new Node(i, new Vector2(x, y)));
            }
            foreach (var outerNode in graph)
            foreach (var innerNode in graph)
                if (innerNode != outerNode)
                    outerNode.AddEdge(new Edge(outerNode, innerNode,
                        Math.Round(outerNode.GetDistanceTo(innerNode), 2)));
            return graph;
        }
References DistributedTravelingSalesman.Domain.Entities.GraphGenerator._random, DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MaxX, DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MaxY, DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MinX, and DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MinY.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateGraph().
GetTwoDimensionalArray< T >()
T[][] DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GetTwoDimensionalArray< T > (int size) inline
Definition at line 63 of file GraphGenerator.cs.
        {
            var array = new T[size][];
            for (var i = 0; i < size; i++)
            {
                var innerArray = new T[size];
                array[i] = innerArray;
            }
            return array;
        }
Field Documentation
_random
readonly Random DistributedTravelingSalesman.Domain.Entities.GraphGenerator._random private
Definition at line 13 of file GraphGenerator.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph(), and DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GraphGenerator().
MaxX
const int DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MaxX = 1000 static private
Definition at line 10 of file GraphGenerator.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph().
MaxY
const int DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MaxY = 1000 static private
Definition at line 12 of file GraphGenerator.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph().
MinX
const int DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MinX = 0 static private
Definition at line 9 of file GraphGenerator.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph().
MinY
const int DistributedTravelingSalesman.Domain.Entities.GraphGenerator.MinY = 0 static private
Definition at line 11 of file GraphGenerator.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.GraphGenerator.GenerateRandomGraph().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman.Domain/Entities/GraphGenerator.cs