courierApp: DistributedTravelingSalesman.Worker.RegisterService Class Reference
DistributedTravelingSalesman.Worker.RegisterService Class Reference
Public Member Functions
RegisterService (IHostApplicationLifetime hostApplicationLifetime, ILogger< RegisterService > logger, IConfiguration configuration)
Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
Properties
static IServerAddressesFeature Addresses [get, set]
Private Member Functions
async Task< string > GetUrl ()
async void OnStarted ()
string FixWildcard (string address)
string GetPort (string address)
Private Attributes
readonly IConfiguration _configuration
readonly IHostApplicationLifetime _hostApplicationLifetime
readonly ILogger< RegisterService > _logger
Detailed Description
Definition at line 14 of file RegisterService.cs.
Constructor & Destructor Documentation
RegisterService()
DistributedTravelingSalesman.Worker.RegisterService.RegisterService (IHostApplicationLifetime hostApplicationLifetime, ILogger< RegisterService > logger, IConfiguration configuration) inline
Definition at line 20 of file RegisterService.cs.
        {
            _hostApplicationLifetime = hostApplicationLifetime;
            _logger = logger;
            _configuration = configuration;
        }
References DistributedTravelingSalesman.Worker.RegisterService._configuration, DistributedTravelingSalesman.Worker.RegisterService._hostApplicationLifetime, and DistributedTravelingSalesman.Worker.RegisterService._logger.
Member Function Documentation
FixWildcard()
string DistributedTravelingSalesman.Worker.RegisterService.FixWildcard (string address) inline private
Definition at line 79 of file RegisterService.cs.
        {
            return address.Replace("[::]", "localhost");
        }
Referenced by DistributedTravelingSalesman.Worker.RegisterService.GetUrl().
GetPort()
string DistributedTravelingSalesman.Worker.RegisterService.GetPort (string address) inline private
Definition at line 84 of file RegisterService.cs.
        {
            var parts = address.Replace("[::]", "").Split(':');
            return parts[2];
        }
GetUrl()
async Task< string > DistributedTravelingSalesman.Worker.RegisterService.GetUrl () inline private
Definition at line 51 of file RegisterService.cs.
        {
            var host = await Dns.GetHostEntryAsync(Dns.GetHostName());
            var ip = host
                .AddressList
                .FirstOrDefault(ip =>
                    ip.AddressFamily == AddressFamily.InterNetwork && ip.ToString().StartsWith("192"));
            return FixWildcard($"http://{ip}:{GetPort(Addresses.Addresses.First())}");
        }
References DistributedTravelingSalesman.Worker.RegisterService.FixWildcard().
Referenced by DistributedTravelingSalesman.Worker.RegisterService.OnStarted(), and DistributedTravelingSalesman.Worker.RegisterService.StopAsync().
OnStarted()
async void DistributedTravelingSalesman.Worker.RegisterService.OnStarted () inline private
Definition at line 63 of file RegisterService.cs.
        {
            var hostInfo = new Domain.Entities.Worker
            {
                Url = await GetUrl()
            };
            var client = new RestClient(_configuration["RegisterUrl"]);
            var request = new RestRequest();
            request.AddJsonBody(hostInfo);
            var response = await client.PostAsync(request);
            if (!response.IsSuccessful)
                _logger?.LogError($"Could not register worker: {response.StatusCode} {response.StatusDescription}");
            else
                _logger?.LogInformation("Successfully registered!");
        }
References DistributedTravelingSalesman.Worker.RegisterService._configuration, DistributedTravelingSalesman.Worker.RegisterService._logger, and DistributedTravelingSalesman.Worker.RegisterService.GetUrl().
Referenced by DistributedTravelingSalesman.Worker.RegisterService.StartAsync().
StartAsync()
Task DistributedTravelingSalesman.Worker.RegisterService.StartAsync (CancellationToken cancellationToken) inline
Definition at line 31 of file RegisterService.cs.
        {
            _hostApplicationLifetime.ApplicationStarted.Register(OnStarted);
            return Task.CompletedTask;
        }
References DistributedTravelingSalesman.Worker.RegisterService._hostApplicationLifetime, and DistributedTravelingSalesman.Worker.RegisterService.OnStarted().
StopAsync()
async Task DistributedTravelingSalesman.Worker.RegisterService.StopAsync (CancellationToken cancellationToken) inline
Definition at line 38 of file RegisterService.cs.
        {
            _logger.LogInformation("Deregistering worker");
            var client = new RestClient(_configuration["RegisterUrl"]);
            var request = new RestRequest();
            request.AddOrUpdateParameter("url", await GetUrl());
            var response = await client.DeleteAsync(request);
            if (!response.IsSuccessful)
                _logger?.LogError($"Could not deregister worker: {response.StatusCode} {response.StatusDescription}");
            else
                _logger?.LogInformation("Successfully deregistered!");
        }
References DistributedTravelingSalesman.Worker.RegisterService._configuration, DistributedTravelingSalesman.Worker.RegisterService._logger, and DistributedTravelingSalesman.Worker.RegisterService.GetUrl().
Field Documentation
_configuration
readonly IConfiguration DistributedTravelingSalesman.Worker.RegisterService._configuration private
Definition at line 16 of file RegisterService.cs.
Referenced by DistributedTravelingSalesman.Worker.RegisterService.OnStarted(), DistributedTravelingSalesman.Worker.RegisterService.RegisterService(), and DistributedTravelingSalesman.Worker.RegisterService.StopAsync().
_hostApplicationLifetime
readonly IHostApplicationLifetime DistributedTravelingSalesman.Worker.RegisterService._hostApplicationLifetime private
Definition at line 17 of file RegisterService.cs.
Referenced by DistributedTravelingSalesman.Worker.RegisterService.RegisterService(), and DistributedTravelingSalesman.Worker.RegisterService.StartAsync().
_logger
readonly ILogger<RegisterService> DistributedTravelingSalesman.Worker.RegisterService._logger private
Definition at line 18 of file RegisterService.cs.
Referenced by DistributedTravelingSalesman.Worker.RegisterService.OnStarted(), DistributedTravelingSalesman.Worker.RegisterService.RegisterService(), and DistributedTravelingSalesman.Worker.RegisterService.StopAsync().
Property Documentation
Addresses
IServerAddressesFeature DistributedTravelingSalesman.Worker.RegisterService.Addresses static get set
Definition at line 29 of file RegisterService.cs.
{ get; set; }
The documentation for this class was generated from the following file:
DistributedTravelingSalesman.Worker/RegisterService.cs