courierApp: DistributedTravelingSalesman.WorkerConnectionHelper Class Reference
DistributedTravelingSalesman.WorkerConnectionHelper Class Reference
Public Member Functions
async Task Initialize ()
async Task< FindBestPartialResultResponseDto > CalculateFor (int begin, IList< int > chunks)
async Task FinalizeSession ()
Static Public Member Functions
static Task< WorkerConnectionHelper > Create (Worker worker, Graph graph)
Private Member Functions
WorkerConnectionHelper (Worker worker, Graph graph)
void ThrowExceptionOnNotSuccessfulResponse (RestResponseBase response)
Private Attributes
readonly Graph _graph
readonly RestClient _restClient
readonly Worker _worker
Detailed Description
Definition at line 12 of file WorkerConnectionHelper.cs.
Constructor & Destructor Documentation
WorkerConnectionHelper()
DistributedTravelingSalesman.WorkerConnectionHelper.WorkerConnectionHelper (Worker worker, Graph graph) inline private
Definition at line 18 of file WorkerConnectionHelper.cs.
        {
            _restClient = new RestClient(worker.Url);
            _worker = worker;
            _graph = graph;
        }
References DistributedTravelingSalesman.WorkerConnectionHelper._graph, DistributedTravelingSalesman.WorkerConnectionHelper._restClient, DistributedTravelingSalesman.WorkerConnectionHelper._worker, and DistributedTravelingSalesman.Domain.Entities.Worker.Url.
Referenced by DistributedTravelingSalesman.WorkerConnectionHelper.Create().
Member Function Documentation
CalculateFor()
async Task< FindBestPartialResultResponseDto > DistributedTravelingSalesman.WorkerConnectionHelper.CalculateFor (int begin, IList< int > chunks) inline
Definition at line 51 of file WorkerConnectionHelper.cs.
        {
            var request = new RestRequest("/api/task/findBestPartialResult");
            request.Timeout = Timeout.Infinite;
            request.AddJsonBody(new FindBestPartialResultRequestDto
            {
                StartIndex = begin,
                Chunks = chunks
            });
            var response = await _restClient.ExecutePostAsync(request).ConfigureAwait(false);
            if (!response.IsSuccessful) ThrowExceptionOnNotSuccessfulResponse(response);
            return JsonSerializer.Deserialize<FindBestPartialResultResponseDto>(response.Content,
                new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
        }
References DistributedTravelingSalesman.WorkerConnectionHelper._restClient, and DistributedTravelingSalesman.WorkerConnectionHelper.ThrowExceptionOnNotSuccessfulResponse().
Create()
static Task< WorkerConnectionHelper > DistributedTravelingSalesman.WorkerConnectionHelper.Create (Worker worker, Graph graph) inline static
Definition at line 25 of file WorkerConnectionHelper.cs.
        {
            var task = Task.Run(async () =>
            {
                var helper = new WorkerConnectionHelper(worker, graph);
                await helper.Initialize();
                return helper;
            });
            return task;
        }
References DistributedTravelingSalesman.WorkerConnectionHelper.WorkerConnectionHelper().
Referenced by DistributedTravelingSalesman.Service.GraphService.GetBestHamiltonianPath().
FinalizeSession()
async Task DistributedTravelingSalesman.WorkerConnectionHelper.FinalizeSession () inline
Definition at line 70 of file WorkerConnectionHelper.cs.
        {
            var request = new RestRequest("/api/task");
            var response = await _restClient.DeleteAsync(request).ConfigureAwait(false);
            if (!response.IsSuccessful) ThrowExceptionOnNotSuccessfulResponse(response);
        }
References DistributedTravelingSalesman.WorkerConnectionHelper._restClient, and DistributedTravelingSalesman.WorkerConnectionHelper.ThrowExceptionOnNotSuccessfulResponse().
Initialize()
async Task DistributedTravelingSalesman.WorkerConnectionHelper.Initialize () inline
Definition at line 39 of file WorkerConnectionHelper.cs.
        {
            var registerRequest = new RestRequest("/api/task/begin");
            registerRequest.AddJsonBody(new BeginTaskRequestDto
            {
                Graph = _graph
            });
            var response = await _restClient.ExecutePostAsync(registerRequest).ConfigureAwait(false);
            if (!response.IsSuccessful) ThrowExceptionOnNotSuccessfulResponse(response);
        }
References DistributedTravelingSalesman.WorkerConnectionHelper._graph, DistributedTravelingSalesman.WorkerConnectionHelper._restClient, and DistributedTravelingSalesman.WorkerConnectionHelper.ThrowExceptionOnNotSuccessfulResponse().
ThrowExceptionOnNotSuccessfulResponse()
void DistributedTravelingSalesman.WorkerConnectionHelper.ThrowExceptionOnNotSuccessfulResponse (RestResponseBase response) inline private
Definition at line 77 of file WorkerConnectionHelper.cs.
        {
            throw response.ResponseStatus == ResponseStatus.Completed
                ? new InvalidOperationException(response.ErrorMessage)
                : new InvalidOperationException($"Worker not responding ({_worker.Url})");
        }
Referenced by DistributedTravelingSalesman.WorkerConnectionHelper.CalculateFor(), DistributedTravelingSalesman.WorkerConnectionHelper.FinalizeSession(), and DistributedTravelingSalesman.WorkerConnectionHelper.Initialize().
Field Documentation
_graph
readonly Graph DistributedTravelingSalesman.WorkerConnectionHelper._graph private
Definition at line 14 of file WorkerConnectionHelper.cs.
Referenced by DistributedTravelingSalesman.WorkerConnectionHelper.Initialize(), and DistributedTravelingSalesman.WorkerConnectionHelper.WorkerConnectionHelper().
_restClient
readonly RestClient DistributedTravelingSalesman.WorkerConnectionHelper._restClient private
Definition at line 15 of file WorkerConnectionHelper.cs.
Referenced by DistributedTravelingSalesman.WorkerConnectionHelper.CalculateFor(), DistributedTravelingSalesman.WorkerConnectionHelper.FinalizeSession(), DistributedTravelingSalesman.WorkerConnectionHelper.Initialize(), and DistributedTravelingSalesman.WorkerConnectionHelper.WorkerConnectionHelper().
_worker
readonly Worker DistributedTravelingSalesman.WorkerConnectionHelper._worker private
Definition at line 16 of file WorkerConnectionHelper.cs.
Referenced by DistributedTravelingSalesman.WorkerConnectionHelper.WorkerConnectionHelper().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman/WorkerConnectionHelper.cs