courierApp: DistributedTravelingSalesman.Controllers.GraphController Class Reference
DistributedTravelingSalesman.Controllers.GraphController Class Reference
Public Member Functions
GraphController (IGraphService graphService, IWorkerService workerService)
async Task< IActionResult > GetBestHamiltonianPath (GetBestHamiltonianPathRequestDto request)
FileStreamResult GenerateGraph (int? numberOfNodes)
Private Attributes
readonly IGraphService _graphService
readonly IWorkerService _workerService
Detailed Description
Definition at line 12 of file GraphController.cs.
Constructor & Destructor Documentation
GraphController()
DistributedTravelingSalesman.Controllers.GraphController.GraphController (IGraphService graphService, IWorkerService workerService) inline
Definition at line 17 of file GraphController.cs.
        {
            _graphService = graphService;
            _workerService = workerService;
        }
References DistributedTravelingSalesman.Controllers.GraphController._graphService, and DistributedTravelingSalesman.Controllers.GraphController._workerService.
Member Function Documentation
GenerateGraph()
FileStreamResult DistributedTravelingSalesman.Controllers.GraphController.GenerateGraph (int? numberOfNodes) inline
Definition at line 32 of file GraphController.cs.
        {
            if (numberOfNodes == null)
                throw new ArgumentNullException(nameof(numberOfNodes));
            var stream = _graphService.GenerateGraph(numberOfNodes.Value);
            return new FileStreamResult(stream, new MediaTypeHeaderValue("text/plain"))
            {
                FileDownloadName = "generatedGraph.json"
            };
        }
References DistributedTravelingSalesman.Controllers.GraphController._graphService, and DistributedTravelingSalesman.Service.IGraphService.GenerateGraph().
GetBestHamiltonianPath()
async Task< IActionResult > DistributedTravelingSalesman.Controllers.GraphController.GetBestHamiltonianPath (GetBestHamiltonianPathRequestDto request) inline
Definition at line 24 of file GraphController.cs.
        {
            var workers = await _workerService.GetOnlineWorkers();
            return Ok(await _graphService.GetBestHamiltonianPath(workers.GetWorkerList(), request));
        }
References DistributedTravelingSalesman.Controllers.GraphController._graphService, DistributedTravelingSalesman.Controllers.GraphController._workerService, DistributedTravelingSalesman.Service.IGraphService.GetBestHamiltonianPath(), and DistributedTravelingSalesman.Service.IWorkerService.GetOnlineWorkers().
Field Documentation
_graphService
readonly IGraphService DistributedTravelingSalesman.Controllers.GraphController._graphService private
Definition at line 14 of file GraphController.cs.
Referenced by DistributedTravelingSalesman.Controllers.GraphController.GenerateGraph(), DistributedTravelingSalesman.Controllers.GraphController.GetBestHamiltonianPath(), and DistributedTravelingSalesman.Controllers.GraphController.GraphController().
_workerService
readonly IWorkerService DistributedTravelingSalesman.Controllers.GraphController._workerService private
Definition at line 15 of file GraphController.cs.
Referenced by DistributedTravelingSalesman.Controllers.GraphController.GetBestHamiltonianPath(), and DistributedTravelingSalesman.Controllers.GraphController.GraphController().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman/Controllers/GraphController.cs