courierApp: DistributedTravelingSalesman.Controllers.WorkerController Class Reference
DistributedTravelingSalesman.Controllers.WorkerController Class Reference
Public Member Functions
WorkerController (IWorkerService workerService)
async Task< IActionResult > GetOnlineWorkers ()
async Task< IActionResult > AddWorker (AddWorkerDto request)
async Task< IActionResult > RemoveWorker ([FromQuery] string url)
Private Attributes
readonly IWorkerService _workerService
Detailed Description
Definition at line 10 of file WorkerController.cs.
Constructor & Destructor Documentation
WorkerController()
DistributedTravelingSalesman.Controllers.WorkerController.WorkerController (IWorkerService workerService) inline
Definition at line 14 of file WorkerController.cs.
        {
            _workerService = workerService;
        }
References DistributedTravelingSalesman.Controllers.WorkerController._workerService.
Member Function Documentation
AddWorker()
async Task< IActionResult > DistributedTravelingSalesman.Controllers.WorkerController.AddWorker (AddWorkerDto request) inline
Definition at line 26 of file WorkerController.cs.
        {
            await _workerService.AddWorker(request);
            return Created("", "");
        }
References DistributedTravelingSalesman.Controllers.WorkerController._workerService, and DistributedTravelingSalesman.Service.IWorkerService.AddWorker().
GetOnlineWorkers()
async Task< IActionResult > DistributedTravelingSalesman.Controllers.WorkerController.GetOnlineWorkers () inline
Definition at line 20 of file WorkerController.cs.
        {
            return Ok(await _workerService.GetOnlineWorkers());
        }
References DistributedTravelingSalesman.Controllers.WorkerController._workerService, and DistributedTravelingSalesman.Service.IWorkerService.GetOnlineWorkers().
RemoveWorker()
async Task< IActionResult > DistributedTravelingSalesman.Controllers.WorkerController.RemoveWorker ([FromQuery] string url) inline
Definition at line 34 of file WorkerController.cs.
        {
            await _workerService.RemoveWorker(new RemoveWorkerDto { Url = url });
            return NoContent();
        }
References DistributedTravelingSalesman.Controllers.WorkerController._workerService, and DistributedTravelingSalesman.Service.IWorkerService.RemoveWorker().
Field Documentation
_workerService
readonly IWorkerService DistributedTravelingSalesman.Controllers.WorkerController._workerService private
Definition at line 12 of file WorkerController.cs.
Referenced by DistributedTravelingSalesman.Controllers.WorkerController.AddWorker(), DistributedTravelingSalesman.Controllers.WorkerController.GetOnlineWorkers(), DistributedTravelingSalesman.Controllers.WorkerController.RemoveWorker(), and DistributedTravelingSalesman.Controllers.WorkerController.WorkerController().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman/Controllers/WorkerController.cs