courierApp: DistributedTravelingSalesman.Domain.Entities.BruteforceSolver Class Reference
DistributedTravelingSalesman.Domain.Entities.BruteforceSolver Class Reference
Public Member Functions
void Clear ()
SolverResult Solve (Graph graph, int startIndex, int firstStep)
Static Private Member Functions
static bool NextPermutation (List< int > list)
Private Attributes
List< int > _currentMinimum = new()
double _currentMinimumRoute = double.MaxValue
List< int > _currentStep = new()
Detailed Description
Definition at line 7 of file BruteforceSolver.cs.
Member Function Documentation
Clear()
void DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Clear () inline
Definition at line 13 of file BruteforceSolver.cs.
        {
            _currentMinimum.Clear();
            _currentMinimumRoute = double.MaxValue;
            _currentStep.Clear();
        }
References DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimum, DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimumRoute, and DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentStep.
NextPermutation()
static bool DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.NextPermutation (List< int > list) inline static private
Definition at line 52 of file BruteforceSolver.cs.
        {
            if (list.Count < 2) return false;
            var k = list.Count - 2;
            while (k >= 0 && list[k].CompareTo(list[k + 1]) >= 0) k--;
            if (k < 0) return false;
            var l = list.Count - 1;
            while (l > k && list[l].CompareTo(list[k]) <= 0) l--;
            list[k] ^= list[l];
            list[l] ^= list[k];
            list[k] ^= list[l];
            var i = k + 1;
            var j = list.Count - 1;
            while (i < j)
            {
                list[i] ^= list[j];
                list[j] ^= list[i];
                list[i] ^= list[j];
                i++;
                j--;
            }
            return true;
        }
Referenced by DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Solve().
Solve()
SolverResult DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Solve (Graph graph, int startIndex, int firstStep) inline
Definition at line 20 of file BruteforceSolver.cs.
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            _currentStep = Enumerable.Range(0, graph.GraphSize).ToList();
            do
            {
                if (_currentStep[0] == startIndex && _currentStep[1] == firstStep)
                {
                    double route = 0;
                    for (var i = 0; i < _currentStep.Count - 1; i++)
                        route += graph.AdjMatrix[_currentStep[i]][_currentStep[i + 1]];
                    if (_currentMinimumRoute > route)
                    {
                        _currentMinimumRoute = route;
                        _currentMinimum = new List<int>(_currentStep);
                    }
                }
            } while (NextPermutation(_currentStep));
            stopwatch.Stop();
            return new SolverResult
            {
                Nodes = new List<int>(_currentMinimum),
                Route = _currentMinimumRoute,
                Time = stopwatch.Elapsed
            };
        }
References DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimum, DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimumRoute, DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentStep, DistributedTravelingSalesman.Domain.Entities.Graph.AdjMatrix, DistributedTravelingSalesman.Domain.Entities.Graph.GraphSize, and DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.NextPermutation().
Field Documentation
_currentMinimum
List<int> DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimum = new() private
Definition at line 9 of file BruteforceSolver.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Clear(), and DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Solve().
_currentMinimumRoute
double DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentMinimumRoute = double.MaxValue private
Definition at line 10 of file BruteforceSolver.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Clear(), and DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Solve().
_currentStep
List<int> DistributedTravelingSalesman.Domain.Entities.BruteforceSolver._currentStep = new() private
Definition at line 11 of file BruteforceSolver.cs.
Referenced by DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Clear(), and DistributedTravelingSalesman.Domain.Entities.BruteforceSolver.Solve().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman.Domain/Entities/BruteforceSolver.cs