courierApp: DistributedTravelingSalesman.Worker.Controllers.TaskController Class Reference
DistributedTravelingSalesman.Worker.Controllers.TaskController Class Reference
Public Member Functions
TaskController (ITaskService taskService, ILogger< TaskController > logger)
IActionResult Begin (BeginTaskRequestDto request)
IActionResult FindBestPartialResult (FindBestPartialResultRequestDto request)
IActionResult Cancel ()
Private Attributes
readonly ILogger< TaskController > _logger
readonly ITaskService _taskService
Detailed Description
Definition at line 10 of file TaskController.cs.
Constructor & Destructor Documentation
TaskController()
DistributedTravelingSalesman.Worker.Controllers.TaskController.TaskController (ITaskService taskService, ILogger< TaskController > logger) inline
Definition at line 15 of file TaskController.cs.
        {
            _taskService = taskService;
            _logger = logger;
        }
References DistributedTravelingSalesman.Worker.Controllers.TaskController._logger, and DistributedTravelingSalesman.Worker.Controllers.TaskController._taskService.
Member Function Documentation
Begin()
IActionResult DistributedTravelingSalesman.Worker.Controllers.TaskController.Begin (BeginTaskRequestDto request) inline
Definition at line 22 of file TaskController.cs.
        {
            _logger.LogInformation("Begin, graph: {}", JsonSerializer.Serialize(request));
            _taskService.StartTask(request.Graph);
            return NoContent();
        }
References DistributedTravelingSalesman.Worker.Controllers.TaskController._logger, DistributedTravelingSalesman.Worker.Controllers.TaskController._taskService, DistributedTravelingSalesman.Dto.BeginTaskRequestDto.Graph, and DistributedTravelingSalesman.Worker.ITaskService.StartTask().
Cancel()
IActionResult DistributedTravelingSalesman.Worker.Controllers.TaskController.Cancel () inline
Definition at line 38 of file TaskController.cs.
        {
            _taskService.CancelCurrentTask();
            return NoContent();
        }
References DistributedTravelingSalesman.Worker.Controllers.TaskController._taskService, and DistributedTravelingSalesman.Worker.ITaskService.CancelCurrentTask().
FindBestPartialResult()
IActionResult DistributedTravelingSalesman.Worker.Controllers.TaskController.FindBestPartialResult (FindBestPartialResultRequestDto request) inline
Definition at line 32 of file TaskController.cs.
        {
            return Ok(_taskService.FindBestPartialResult(request));
        }
References DistributedTravelingSalesman.Worker.Controllers.TaskController._taskService, and DistributedTravelingSalesman.Worker.ITaskService.FindBestPartialResult().
Field Documentation
_logger
readonly ILogger<TaskController> DistributedTravelingSalesman.Worker.Controllers.TaskController._logger private
Definition at line 12 of file TaskController.cs.
Referenced by DistributedTravelingSalesman.Worker.Controllers.TaskController.Begin(), and DistributedTravelingSalesman.Worker.Controllers.TaskController.TaskController().
_taskService
readonly ITaskService DistributedTravelingSalesman.Worker.Controllers.TaskController._taskService private
Definition at line 13 of file TaskController.cs.
Referenced by DistributedTravelingSalesman.Worker.Controllers.TaskController.Begin(), DistributedTravelingSalesman.Worker.Controllers.TaskController.Cancel(), DistributedTravelingSalesman.Worker.Controllers.TaskController.FindBestPartialResult(), and DistributedTravelingSalesman.Worker.Controllers.TaskController.TaskController().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman.Worker/Controllers/TaskController.cs