courierApp: DistributedTravelingSalesman.Service.WorkerService Class Reference
DistributedTravelingSalesman.Service.WorkerService Class Reference
Public Member Functions
WorkerService (ILogger< IWorkerService > logger)
Task< GetOnlineWorkersResponseDto > GetOnlineWorkers ()
Task AddWorker (AddWorkerDto request)
Task RemoveWorker (RemoveWorkerDto request)
Task< GetOnlineWorkersResponseDto > GetOnlineWorkers ()
Task AddWorker (AddWorkerDto request)
Task RemoveWorker (RemoveWorkerDto request)
Private Attributes
readonly ILogger< IWorkerService > _logger
readonly ConcurrentDictionary< string, Worker > _registeredWorkers = new()
Detailed Description
Definition at line 11 of file WorkerService.cs.
Constructor & Destructor Documentation
WorkerService()
DistributedTravelingSalesman.Service.WorkerService.WorkerService (ILogger< IWorkerService > logger) inline
Definition at line 17 of file WorkerService.cs.
        {
            _logger = logger;
        }
References DistributedTravelingSalesman.Service.WorkerService._logger.
Member Function Documentation
AddWorker()
Task DistributedTravelingSalesman.Service.WorkerService.AddWorker (AddWorkerDto request) inline
Implements DistributedTravelingSalesman.Service.IWorkerService.
Definition at line 34 of file WorkerService.cs.
        {
            if (_registeredWorkers.ContainsKey(request.Url))
                throw new InvalidOperationException($"Worker with given url ({request.Url}) already exists");
            var worker = Worker.Create(request.Url);
            _registeredWorkers.TryAdd(worker.Url, worker);
            _logger.LogInformation($"Registered {request.Url} worker");
            return Task.CompletedTask;
        }
References DistributedTravelingSalesman.Service.WorkerService._logger, DistributedTravelingSalesman.Service.WorkerService._registeredWorkers, DistributedTravelingSalesman.Domain.Entities.Worker.Create(), and DistributedTravelingSalesman.Dto.AddWorkerDto.Url.
GetOnlineWorkers()
Task< GetOnlineWorkersResponseDto > DistributedTravelingSalesman.Service.WorkerService.GetOnlineWorkers () inline
Implements DistributedTravelingSalesman.Service.IWorkerService.
Definition at line 22 of file WorkerService.cs.
        {
            return Task.FromResult(new GetOnlineWorkersResponseDto
            {
                Data = _registeredWorkers.Select(x => new GetOnlineWorkersResponseDto.ListItem
                {
                    Id = x.Value.Id,
                    Url = x.Value.Url
                })
            });
        }
References DistributedTravelingSalesman.Service.WorkerService._registeredWorkers.
RemoveWorker()
Task DistributedTravelingSalesman.Service.WorkerService.RemoveWorker (RemoveWorkerDto request) inline
Implements DistributedTravelingSalesman.Service.IWorkerService.
Definition at line 46 of file WorkerService.cs.
        {
            if (_registeredWorkers.ContainsKey(request.Url) == false)
                throw new InvalidOperationException($"Worker with given url ({request.Url}) does not exist");
            _registeredWorkers.TryRemove(request.Url, out _);
            _logger.LogInformation($"Deregistered {request.Url} worker");
            return Task.CompletedTask;
        }
References DistributedTravelingSalesman.Service.WorkerService._logger, DistributedTravelingSalesman.Service.WorkerService._registeredWorkers, and DistributedTravelingSalesman.Dto.RemoveWorkerDto.Url.
Field Documentation
_logger
readonly ILogger<IWorkerService> DistributedTravelingSalesman.Service.WorkerService._logger private
Definition at line 13 of file WorkerService.cs.
Referenced by DistributedTravelingSalesman.Service.WorkerService.AddWorker(), DistributedTravelingSalesman.Service.WorkerService.RemoveWorker(), and DistributedTravelingSalesman.Service.WorkerService.WorkerService().
_registeredWorkers
readonly ConcurrentDictionary<string, Worker> DistributedTravelingSalesman.Service.WorkerService._registeredWorkers = new() private
Definition at line 15 of file WorkerService.cs.
Referenced by DistributedTravelingSalesman.Service.WorkerService.AddWorker(), DistributedTravelingSalesman.Service.WorkerService.GetOnlineWorkers(), and DistributedTravelingSalesman.Service.WorkerService.RemoveWorker().
The documentation for this class was generated from the following file:
DistributedTravelingSalesman/Service/WorkerService.cs