courierApp: DistributedTravelingSalesman.Worker.ITaskService Interface Reference
DistributedTravelingSalesman.Worker.ITaskService Interface Reference
Public Member Functions
void StartTask (Graph graph)
FindBestPartialResultResponseDto FindBestPartialResult (FindBestPartialResultRequestDto request)
void CancelCurrentTask ()
Detailed Description
Definition at line 6 of file ITaskService.cs.
Member Function Documentation
CancelCurrentTask()
void DistributedTravelingSalesman.Worker.ITaskService.CancelCurrentTask ()
Implemented in DistributedTravelingSalesman.Worker.TaskService.
Referenced by DistributedTravelingSalesman.Worker.Controllers.TaskController.Cancel().
FindBestPartialResult()
FindBestPartialResultResponseDto DistributedTravelingSalesman.Worker.ITaskService.FindBestPartialResult (FindBestPartialResultRequestDto request)
Implemented in DistributedTravelingSalesman.Worker.TaskService.
Referenced by DistributedTravelingSalesman.Worker.Controllers.TaskController.FindBestPartialResult().
StartTask()
void DistributedTravelingSalesman.Worker.ITaskService.StartTask (Graph graph)
Implemented in DistributedTravelingSalesman.Worker.TaskService.
Referenced by DistributedTravelingSalesman.Worker.Controllers.TaskController.Begin().
The documentation for this interface was generated from the following file:
DistributedTravelingSalesman.Worker/ITaskService.cs