courierApp: DistributedTravelingSalesman.Service.IWorkerService Interface Reference
DistributedTravelingSalesman.Service.IWorkerService Interface Reference
Public Member Functions
Task< GetOnlineWorkersResponseDto > GetOnlineWorkers ()
Task AddWorker (AddWorkerDto request)
Task RemoveWorker (RemoveWorkerDto request)
Detailed Description
Definition at line 6 of file IWorkerService.cs.
Member Function Documentation
AddWorker()
Task DistributedTravelingSalesman.Service.IWorkerService.AddWorker (AddWorkerDto request)
Implemented in DistributedTravelingSalesman.Service.WorkerService.
Referenced by DistributedTravelingSalesman.Controllers.WorkerController.AddWorker().
GetOnlineWorkers()
Task< GetOnlineWorkersResponseDto > DistributedTravelingSalesman.Service.IWorkerService.GetOnlineWorkers ()
Implemented in DistributedTravelingSalesman.Service.WorkerService.
Referenced by DistributedTravelingSalesman.Controllers.GraphController.GetBestHamiltonianPath(), and DistributedTravelingSalesman.Controllers.WorkerController.GetOnlineWorkers().
RemoveWorker()
Task DistributedTravelingSalesman.Service.IWorkerService.RemoveWorker (RemoveWorkerDto request)
Implemented in DistributedTravelingSalesman.Service.WorkerService.
Referenced by DistributedTravelingSalesman.Controllers.WorkerController.RemoveWorker().
The documentation for this interface was generated from the following file:
DistributedTravelingSalesman/Service/IWorkerService.cs